apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-image-test-1
  namespace: my-test
  labels:
    app: test-1
spec:
  selector:
    matchLabels:
      app: test-1
  template:
    metadata:
      labels:
        app: test-1
    spec:
      containers:
      - name: uses-private-image
        image: hihikim92/msvc_template:latest
        imagePullPolicy: Always
        command:
        - python
        - msvc_templete.py
        args:
        - --sleep_time
        - "1.0"
        - --port
        - "8888"
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: test-svc-1
  namespace: my-test
spec:
  selector:
    app: test-1
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8888
