apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-image-test-2
  labels:
    app: test-2
spec:
  selector:
    matchLabels:
      app: test-2
  template:
    metadata:
      labels:
        app: test-2
    spec:
      containers:
      - name: uses-private-image
        image: hihikim92/msvc_template:latest
        imagePullPolicy: Always
        command: ["python", "msvc_templete.py"]
        args: ["--sleep_time","1.0", "--port", "8888","--next_address","http://test-svc-1:4000"]
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: test-svc-2
spec:
  selector:
    app: test-2
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8888
